<a href="https://colab.research.google.com/github/alok3452/-LGMVIP-JANUARY/blob/main/Untitled19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import os
import plotly.express as px
import xgboost as xgb
from sklearn import metrics
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import MinMaxScaler
from sklearn import model_selection
from sklearn.model_selection import StratifiedKFold
import gc
from sklearn.ensemble import ExtraTreesClassifier, AdaBoostClassifier
gc.enable()
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
train_df = pd.read_csv('../content/train.csv (1).csv', dtype={'major': str})
test_df = pd.read_csv('../content/test.csv', dtype={'major':str})

In [ ]:
train_df.shape

(15730, 16)

In [ ]:
test_df.shape

(5244, 14)

In [ ]:
train_df.head()

,id,title,Rating,maincateg,platform,price1,actprice1,Offer %,norating1,noreviews1,star_5f,star_4f,star_3f,star_2f,star_1f,fulfilled1
0,16695,Fashionable & Comfortable Bellies For Women (...,3.9,Women,Flipkart,698,999,30.13%,38.0,7.0,17.0,9.0,6.0,3,3,0
1,5120,Combo Pack of 4 Casual Shoes Sneakers For Men ...,3.8,Men,Flipkart,999,1999,50.03%,531.0,69.0,264.0,92.0,73.0,29,73,1
2,18391,Cilia Mode Leo Sneakers For Women (White),4.4,Women,Flipkart,2749,4999,45.01%,17.0,4.0,11.0,3.0,2.0,1,0,1
3,495,Men Black Sports Sandal,4.2,Men,Flipkart,518,724,15.85%,46413.0,6229.0,1045.0,12416.0,5352.0,701,4595,1
4,16408,Men Green Sports Sandal,3.9,Men,Flipkart,1379,2299,40.02%,77.0,3.0,35.0,21.0,7.0,7,7,1

In [ ]:
test_df.head()

,id,title,Rating,maincateg,platform,actprice1,norating1,noreviews1,star_5f,star_4f,star_3f,star_2f,star_1f,fulfilled1
0,2242,Casuals For Men (Blue),3.8,Men,Flipkart,999,27928,3543,14238.0,4295,3457,1962,3976.0,1
1,20532,Women Black Flats Sandal,3.9,Women,Flipkart,499,3015,404,1458.0,657,397,182,321.0,1
2,10648,Women Gold Wedges Sandal,3.9,Women,Flipkart,999,449,52,229.0,70,71,33,46.0,1
3,20677,Men's Height Increasing High Heel Formal Party...,3.9,Men,Flipkart,2999,290,40,141.0,51,49,17,32.0,1
4,12593,Loafers For Men (Tan),3.9,Men,Flipkart,999,2423,326,1265.0,414,293,143,308.0,0

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15730 entries, 0 to 15729
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          15730 non-null  int64
 1   title       15730 non-null  object
 2   Rating      15730 non-null  float64
 3   maincateg   15204 non-null  object
 4   platform    15730 non-null  object
 5   price1      15730 non-null  int64
 6   actprice1   15730 non-null  int64
 7   Offer %     15730 non-null  object
 8   norating1   15052 non-null  float64
 9   noreviews1  15152 non-null  float64
 10  star_5f     15142 non-null  float64
 11  star_4f     15191 non-null  float64
 12  star_3f     15499 non-null  float64
 13  star_2f     15730 non-null  int64
 14  star_1f     15730 non-null  int64
 15  fulfilled1  15730 non-null  int64
dtypes: float64(6), int64(6), object(4)
memory usage: 1.9+ MB

In [ ]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5244 entries, 0 to 5243
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          5244 non-null   int64
 1   title       5244 non-null   object
 2   Rating      5041 non-null   float64
 3   maincateg   5177 non-null   object
 4   platform    5244 non-null   object
 5   actprice1   5244 non-null   int64
 6   norating1   5244 non-null   int64
 7   noreviews1  5244 non-null   int64
 8   star_5f     5176 non-null   float64
 9   star_4f     5244 non-null   int64
 10  star_3f     5244 non-null   int64
 11  star_2f     5244 non-null   int64
 12  star_1f     5058 non-null   float64
 13  fulfilled1  5244 non-null   int64
dtypes: float64(3), int64(8), object(3)
memory usage: 573.7+ KB

In [ ]:
train_df.describe()

,id,Rating,price1,actprice1,norating1,noreviews1,star_5f,star_4f,star_3f,star_2f,star_1f,fulfilled1
count,15730.000000,15730.000000,15730.000000,15730.000000,15052.000000,15152.000000,15142.000000,15191.000000,15499.000000,15730.000000,15730.000000,15730.000000
mean,10479.541577,4.012873,688.070693,1369.286777,3057.660776,423.976307,1585.239466,655.923310,357.260662,155.085188,275.500572,0.601526
std,6080.166276,0.298440,649.409586,1240.900227,11846.965689,1768.230384,6177.476241,2855.735531,1402.246610,558.650254,958.589075,0.489600
min,3.000000,0.000000,69.000000,42.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5212.000000,3.900000,349.000000,699.000000,63.000000,9.000000,30.000000,12.000000,7.000000,3.000000,6.000000,0.000000
50%,10458.500000,4.000000,474.000000,999.000000,308.000000,44.000000,150.000000,60.000000,34.000000,17.000000,30.000000,1.000000
75%,15766.750000,4.200000,699.000000,1299.000000,1526.000000,215.000000,788.000000,300.000000,172.000000,77.000000,140.000000,1.000000
max,20973.000000,5.000000,5998.000000,13499.000000,289973.000000,45448.000000,151193.000000,74037.000000,34978.000000,11705.000000,18060.000000,1.000000

In [ ]:
test_df.describe()

,id,Rating,actprice1,norating1,noreviews1,star_5f,star_4f,star_3f,star_2f,star_1f,fulfilled1
count,5244.000000,5041.000000,5244.000000,5244.000000,5244.000000,5176.000000,5244.000000,5244.000000,5244.000000,5058.000000,5244.000000
mean,10507.372616,4.011089,1378.657895,2988.580092,415.491037,1557.443199,639.785469,356.356789,154.139969,270.397786,0.604500
std,5978.658892,0.301915,1280.630070,12881.253715,1910.726669,6583.766998,2991.065223,1632.732834,611.006799,1035.085288,0.489004
min,0.000000,0.000000,139.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5286.750000,3.900000,699.000000,66.000000,9.000000,32.000000,12.000000,7.000000,3.000000,6.000000,0.000000
50%,10561.500000,4.000000,999.000000,307.000000,44.000000,156.000000,61.000000,34.000000,16.000000,29.000000,1.000000
75%,15636.750000,4.200000,1299.000000,1428.000000,214.250000,764.250000,310.250000,166.000000,75.000000,131.000000,1.000000
max,20964.000000,5.000000,15999.000000,289973.000000,45448.000000,151193.000000,74037.000000,49924.000000,12629.000000,23139.000000,1.000000

In [ ]:
train_df.isnull().sum()

id              0
title           0
Rating          0
maincateg     526
platform        0
price1          0
actprice1       0
Offer %         0
norating1     678
noreviews1    578
star_5f       588
star_4f       539
star_3f       231
star_2f         0
star_1f         0
fulfilled1      0
dtype: int64

In [ ]:
test_df.isnull().sum()

id              0
title           0
Rating        203
maincateg      67
platform        0
actprice1       0
norating1       0
noreviews1      0
star_5f        68
star_4f         0
star_3f         0
star_2f         0
star_1f       186
fulfilled1      0
dtype: int64

In [ ]:
train_df.columns

Index(['id', 'title', 'Rating', 'maincateg', 'platform', 'price1', 'actprice1',
       'Offer %', 'norating1', 'noreviews1', 'star_5f', 'star_4f', 'star_3f',
       'star_2f', 'star_1f', 'fulfilled1'],
      dtype='object')

In [ ]:
test_df.columns

Index(['id', 'title', 'Rating', 'maincateg', 'platform', 'actprice1',
       'norating1', 'noreviews1', 'star_5f', 'star_4f', 'star_3f', 'star_2f',
       'star_1f', 'fulfilled1'],
      dtype='object')

In [ ]:
train_df.duplicated().sum()

0

In [ ]:
train_df = train_df.drop_duplicates()

In [ ]:
px.bar(train_df.price1.value_counts())

In [ ]:
px.bar(train_df.actprice1.value_counts())

In [ ]:
train = train_df.copy()
test = test_df.copy()

In [ ]:
# cols_to_drop = []
# for col in train.columns:
#     if col not in test.columns:
#         cols_to_drop.append(col)

In [ ]:
cols_to_drop = ['price1', 'Offer %']

In [ ]:
def parse_dates(train):
    train['platform'] = pd.to_datetime(train['platform'], format = "%Y-%m-%d %X")
    train['price1'] = pd.to_datetime(train['price1'], format = "%Y-%m-%d %X")
    train['actprice1'] = pd.to_datetime(train['actprice1'], format = "%Y-%m-%d %X")
    train['Ofeer %'] = pd.to_datetime(train['Offer %'], format = "%Y-%m-%d %X")
#     train['norating1'] = pd.to_datetime(train['norating1'], format = "%Y-%m-%d %X")
#     train['noreviews1'] = pd.to_datetime(train['noreviews1'], format = "%Y-%m-%d %X")
#     train['star_5f'] = pd.to_datetime(train['star_5f'], format = "%Y-%m-%d %X")
    
    return train

In [ ]:
train = parse_Rating(train)
test = parse_Rating(test)

NameError: ignored